# Application dependencies

require:
    - play
    - localModule -> heroku 0.3

repositories:
    - localModule:
        type: local
        artifact: "${application.path}/../../dist/[module]-[revision].zip"
        contains:
            - localModule -> *
